export const appRoutes = [
    { path: "/dashboard", title: "Dashboard" },
    { path: "/banking", title: "Banking" },
    { path: "/telephone", title: "Telephone" },
    { path: "/accounting", title: "Accounting" },
    { path: "/verkout", title: "Verkout" },
    { path: "/statistics", title: "Statistics" },
    { path: "/administration", title: "Administration" },
    { path: "/post_office", title: "Post Office" },
    { path: "/help", title: "Help" },
    { path: "/warenbestand", title: "Warenbestand" },
    { path: "/test", title: "Test" },
    { path: "/reports", title: "Reports" },
    { path: "/orders", title: "Orders" },
    { path: "/customers", title: "Customers" },
    { path: "/settings", title: "Settings" },
    { path: "/calendar", title: "Calendar" },
    { path: "/messages", title: "Messages" },
    { path: "/inventory", title: "Inventory" },
    { path: "/analytics", title: "Analytics" },
    { path: "/profile", title: "Profile" },
    { path: "/archive", title: "Archive" },
    { path: "/test1", title: "Test1" },
    { path: "/test2", title: "Test2" },
];
